language: generic

env:
  global:
    - export OMP_NUM_THREADS=2
    - export CXX_STANDARD=11

matrix:
  include:
    - name: Linux, modern GCC
      env: CC=gcc-8 CXX=g++-8
      os: linux
      addons: &gcc8
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - python3-pip
            - python3.4-venv

    - name: macOS, modern Clang
      env: CC=/usr/local/opt/llvm/bin/clang
      env: CXX=/usr/local/opt/llvm/bin/clang++
      os: osx
      sudo: false
      before_install:
        - brew update
        - brew install llvm
        - brew install libomp
        - if brew outdated | grep -q python; then brew upgrade python; fi

    - name: Linux, legacy GCC 4.9
      env: CC=gcc-4.9 CXX=g++-4.9
      os: linux
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
            - python3-pip
            - python3.4-venv

    - name: Linux, legacy Clang 3.8
      env: CC="clang-3.8" CXX="clang++-3.8"
      os: linux
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - clang-3.8
            - libiomp-dev
            - python3-pip
            - python3.4-venv

    - name: macOS (xcode8), GCC 6
      env: CC=gcc-6 CXX=g++-6
      os: osx
      osx_image: xcode8
      sudo: false
      before_install:
        - brew update
        - brew cask uninstall --force oclint # See https://github.com/travis-ci/travis-ci/issues/8826 for details.
        - brew install gcc@6
        - if brew outdated | grep -q python; then brew upgrade python; fi

    - name: macOS, legacy Clang 4
      env: CC=/usr/local/opt/llvm@4/bin/clang
      env: CXX=/usr/local/opt/llvm@4/bin/clang++
      os: osx
      sudo: false
      before_install:
        - brew update
        - brew install llvm@4
        - brew install libomp
        - if brew outdated | grep -q python; then brew upgrade python; fi

    - name: macOS, AppleClang
      env: CC=cc CXX=c++
      os: osx
      sudo: false
      before_install:
        - brew install libomp
        - brew upgrade cmake # cmake on osx images (xode9.4) is on 3.11.4 - 3.12+ required 

    # Test more exotic builds only on Linux.
    - name: "Linux, modern GCC: Core build, debugging"
      env: CC=gcc-8 CXX=g++-8
      os: linux
      addons: *gcc8
      script:
        - $CXX --version
        - mkdir debug_test && cd "$_"
        - cmake -DNETWORKIT_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug ..
        - make -j2
        - ctest -V

    - name: "Linux, modern GCC: Core build, non-monolithic"
      env: CC=gcc-8 CXX=g++-8
      os: linux
      addons: *gcc8
      script:
        - $CXX --version
        - mkdir build_non_monolith && cd "$_"
        - cmake -DNETWORKIT_MONOLITH=OFF -DCMAKE_BUILD_TYPE=Debug ..
        - make -j2
        - ctest -V

    # Finally, test conformance to newer versions of the C++ standard.
    - name: C++14 conformance
      env: CC=gcc-8 CXX=g++-8 CXX_STANDARD=14
      os: linux
      addons: *gcc8
      script: &script_cpp_only
        - $CXX --version
        - mkdir debug_test && cd "$_"
        - cmake -DNETWORKIT_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DNETWORKIT_CXX_STANDARD=$CXX_STANDARD ..
        - make -j2
        - ctest -V

    - name: C++17 conformance
      env: CC=gcc-8 CXX=g++-8 CXX_STANDARD=17
      os: linux
      addons: *gcc8
      script: *script_cpp_only

  allow_failures:
    - name: macOS, modern Clang
    - name: macOS, legacy Clang 4 
    - name: macOS (xcode8), GCC 6

script:
 - $CXX --version
 - python3 --version
 - cmake --version

 - python3 -m venv pyenv && . pyenv/bin/activate
 - pip3 install --upgrade pip
 # cython is required because git does not contain _NetworKit.
 # ipython is required for tests.
 - pip3 install cython ipython

 # First, build the C++ core library and run C++ tests.
 - mkdir core_build && cd "$_"
 - cmake -DNETWORKIT_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DNETWORKIT_CXX_STANDARD=$CXX_STANDARD ..
 - make -j2
 - ctest -V
 - cd ..

 # Finally, build the Python extension and run Python tests.
 - export CMAKE_LIBRARY_PATH=${CMAKE_LIBRARY_PATH:+$CMAKE_LIBRARY_PATH:}$(pwd)/core_build
 - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$(pwd)/core_build
 - NETWORKIT_PARALLEL_JOBS=2 python3 ./setup.py build_ext --inplace --networkit-external-core
 - NETWORKIT_PARALLEL_JOBS=2 pip3 install -e .
 - python3 -m unittest discover -v networkit/test/

notifications:
  email: false
