name: Python package

on: [push]

jobs:
  build_mac:
    runs-on: macOS-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Pull submodules
      run: git submodule update --init
    - name: Install system dependencies
      run: |
        brew update
        brew install libomp
        brew upgrade cmake
        brew reinstall gcc
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython wheel twine
    - name: Build
      run: |
        CC=gcc-9 python setup.py build_ext install
    - name: Smoke test
      run: |
        cd /tmp
        python -c "import networkit; networkit.Graph(5)"
    - name: Tests
      run: python -m unittest discover -v networkit/test/
    - name: Build wheel
      run: |
        CC=gcc-9 python setup.py build_ext sdist bdist_wheel
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload --repository-url https://pypi.scm.io/simple dist/*.whl
        
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Pull submodules
      run: git submodule update --init
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython wheel twine
    # - name: Build
    #   run: |
    #     python setup.py build_ext install
    - name: Build with manylinux2010
      run: |
        docker run \
          -v$(pwd):/app \
          -w/app \
          quay.io/pypa/manylinux2010_x86_64 \
          bash -c "
            for PYBIN in /opt/python/*/bin; do
              echo '-->' \$PYBIN
              \$PYBIN/pip install cython
              \$PYBIN/python setup.py build_ext install
              \$PYBIN/python setup.py sdist bdist_wheel -p manylinux2010_x86_64
            done"
    - name: Try to import on different python versions
      run: |
        docker run \
          -v$(pwd):/app \
          quay.io/pypa/manylinux2010_x86_64 \
          bash -c "
            for PYBIN in /opt/python/*/bin; do
              echo '-->' \$PYBIN
              \$PYBIN/pip install /app/python/dist/*-py3-none-manylinux2010_x86_64.whl
              \$PYBIN/python -c 'import networkit; networkit.Graph(5)'
              \$PYBIN/python -m unittest discover -v networkit/test/
            done"
    - name: Smoke test
      run: |
        cd /tmp
        python -c "import networkit; networkit.Graph(5)"
    - name: Tests
      run: python -m unittest discover -v networkit/test/
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload --repository-url https://pypi.scm.io/simple dist/*.whl
